### ISSUE TITLE
error loading it on 1.12.2

### ISSUE THREAD

**Issue by madtomic** [filoghost/TouchscreenHolograms#1]
```java
[08:21:56 INFO]: [TouchscreenHolograms] Enabling TouchscreenHolograms v1.4.0
[08:21:56 WARN]: [] java.io.IOException: The system cannot find the path specified
[08:21:56 WARN]: []     at java.io.WinNTFileSystem.createFileExclusively(Native Method)
[08:21:56 WARN]: []     at java.io.File.createNewFile(Unknown Source)
[08:21:56 WARN]: []     at com.gmail.filoghost.touchscreen.disk.ConfigBase.load(ConfigBase.java:38)
[08:21:56 WARN]: []     at com.gmail.filoghost.touchscreen.disk.Settings.load(Settings.java:33)
[08:21:56 WARN]: []     at com.gmail.filoghost.touchscreen.TouchscreenHolograms.onEnable(TouchscreenHolograms.java:51)
[08:21:56 WARN]: []     at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264)
[08:21:56 WARN]: []     at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:316)
[08:21:56 WARN]: []     at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405)
[08:21:56 WARN]: []     at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugin(CraftServer.java:342)
[08:21:56 WARN]: []     at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugins(CraftServer.java:291)
[08:21:57 WARN]: []     at net.minecraft.server.v1_12_R1.MinecraftServer.t(MinecraftServer.java:442)
[08:21:57 WARN]: []     at net.minecraft.server.v1_12_R1.MinecraftServer.l(MinecraftServer.java:403)
[08:21:57 WARN]: []     at net.minecraft.server.v1_12_R1.MinecraftServer.a(MinecraftServer.java:341)
[08:21:57 WARN]: []     at net.minecraft.server.v1_12_R1.DedicatedServer.init(DedicatedServer.java:289)
[08:21:57 WARN]: []     at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:616)
[08:21:57 WARN]: []     at java.lang.Thread.run(Unknown Source)
[08:21:57 INFO]: [] CUSTOM TERRAIN: Scots pine forest
[08:21:57 INFO]: []
[08:21:57 INFO]: [] ******************************************************
[08:21:57 INFO]: []      Could not load config.yml.
[08:21:57 INFO]: []      TouchscreenHolograms will be disabled.
[08:21:57 INFO]: [] ******************************************************
[08:21:57 INFO]: []
```

**Comment by madtomic** [comment]
Downgrade to 1.3.2 as 1.4.0 is built for 1.13.x
