### ISSUE TITLE
Cannot load plugin

### ISSUE THREAD

**Issue by YourCoal** [filoghost/TouchscreenHolograms#4]
This relates to #1 , however I am using 1.14.2 and tried the latest HolographicDisplays release and the dev build, it gives the same file error.

> [20:32:54] [Server thread/INFO]: [TouchscreenHolograms] Enabling TouchscreenHolograms v1.4.0
[20:32:54] [Server thread/WARN]: java.io.IOException: The system cannot find the path specified
[20:32:54] [Server thread/WARN]: 	at java.base/java.io.File.createNewFile(File.java:1024)
[20:32:54] [Server thread/WARN]: 	at com.gmail.filoghost.touchscreen.disk.ConfigBase.load(ConfigBase.java:38)
[20:32:54] [Server thread/WARN]: 	at com.gmail.filoghost.touchscreen.disk.Settings.load(Settings.java:33)
[20:32:54] [Server thread/WARN]: 	at com.gmail.filoghost.touchscreen.TouchscreenHolograms.onEnable(TouchscreenHolograms.java:51)
[20:32:54] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263)
[20:32:54] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:352)
[20:32:54] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:416)
[20:32:54] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_14_R1.CraftServer.enablePlugin(CraftServer.java:458)
[20:32:54] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_14_R1.CraftServer.enablePlugins(CraftServer.java:372)
[20:32:54] [Server thread/WARN]: 	at net.minecraft.server.v1_14_R1.MinecraftServer.a(MinecraftServer.java:440)
[20:32:54] [Server thread/WARN]: 	at net.minecraft.server.v1_14_R1.DedicatedServer.init(DedicatedServer.java:258)
[20:32:54] [Server thread/WARN]: 	at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:761)
[20:32:54] [Server thread/WARN]: 	at java.base/java.lang.Thread.run(Thread.java:825)
[20:32:54] [Server thread/INFO]: 
 
******************************************************
     Could not load config.yml.
     TouchscreenHolograms will be disabled.
******************************************************

**Comment by filoghost** [comment]
Fixed in https://github.com/filoghost/TouchscreenHolograms/commit/94f2dfda5ee38d8ebbdd5a6a9ba36aaa09357776, I will soon put a release on Bukkit Dev.
