### ISSUE TITLE
Plugin won't load properly on 1.18.2

### ISSUE THREAD

**Issue by pipicat648** [filoghost/TouchscreenHolograms#9]
so when loading this plugin on paper 1.18.2, it loads up, but the commands don't work.
using the latest holographic displays

below is server log

[19:16:52] [Server thread/WARN]: [TouchscreenHolograms] Task #14 for TouchscreenHolograms v1.4.4 generated an exception
java.lang.NoClassDefFoundError: me/filoghost/holographicdisplays/api/hologram/line/HologramLineClickListener
	at me.filoghost.touchscreenholograms.TouchscreenHolograms.lambda$onEnable$1(TouchscreenHolograms.java:92) ~[TouchscreenHolograms.jar:?]
	at org.bukkit.craftbukkit.v1_18_R2.scheduler.CraftTask.run(CraftTask.java:101) ~[paper-1.18.2.jar:git-Paper-387]
	at org.bukkit.craftbukkit.v1_18_R2.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:483) ~[paper-1.18.2.jar:git-Paper-387]
	at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1532) ~[paper-1.18.2.jar:git-Paper-387]
	at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:483) ~[paper-1.18.2.jar:git-Paper-387]
	at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1456) ~[paper-1.18.2.jar:git-Paper-387]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1226) ~[paper-1.18.2.jar:git-Paper-387]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:316) ~[paper-1.18.2.jar:git-Paper-387]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: java.lang.ClassNotFoundException: me.filoghost.holographicdisplays.api.hologram.line.HologramLineClickListener
	at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:151) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:103) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
	... 9 more

**Comment by filoghost** [comment]
Please update Holographic Displays to the latest development build: https://ci.codemc.org/job/filoghost/job/HolographicDisplays
